name: Build and Push Docker Image

on:
  push:
    branches:
      - main # 当代码推送到 main 分支时触发此工作流

env:
  # 定义镜像名称，请替换为你的 Docker Hub 用户名和镜像名
  DOCKER_IMAGE_NAME: yanghongming2000/neko-api-key-tool

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 虚拟机上运行

    steps:
      - name: Checkout code # 步骤1: 检出仓库代码
        uses: actions/checkout@v4

      - name: Log in to Docker Hub # 步骤2: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # 使用 GitHub Secrets 中的用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # 使用 GitHub Secrets 中的密码 (Access Token)

      - name: Build and push Docker image # 步骤3: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile 的上下文路径，. 表示当前仓库的根目录
          file: ./Dockerfile # Dockerfile 的路径
          push: true # 构建完成后推送镜像到仓库
          tags: 
            - ${{ env.DOCKER_IMAGE_NAME }}:latest
            - ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          # 上面两行是实际的标签定义，下面的注释是给 YAML 文件看的，而不是标签的一部分
          # ${{ env.DOCKER_IMAGE_NAME }}:latest 是最新版本标签
          # ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} 是使用 commit SHA 作为标签，方便版本追溯  
